### ISSUE TITLE
error when start app.

### ISSUE THREAD

**Issue by lyquocnam** [cheersjosh/corona#1]
meteor 1.3 beta 16 error on windows [error](https://github.com/meteor/meteor/issues/6448)
so i downgrade to meteor 1.3 beta.12
and run 
`meteor`
all build ok
but on browser is white screen and this error
`Uncaught Invariant Violation: _registerComponent(...): Target container is not a DOM element.`
![redux](https://cloud.githubusercontent.com/assets/8347826/13744853/eb4400ac-e9a7-11e5-928c-94b7bb8f4ab3.PNG)

**Comment by cheersjosh** [comment]
I've updated the release file to use METEOR@1.3-rc.1, could you try again @lyquocnam ?

**Comment by lyquocnam** [comment]
1.3-rc.1 still not work on windows 10 x64 :D may be waiting for next release :3
i really like this project so much !
thanks mr @cheersjosh

**Comment by cheersjosh** [comment]
No problem @lyquocnam . From my research, it seems to be a problem with the Meteor core. So I'll close this issue for the time being. Ps. I'll continue working on enhancements and features to this repo over the weekend.

**Comment by lyquocnam** [comment]
thanks so much mr @cheersjosh !
